remove redundant steps

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,108 +1,109 @@
-version: '2.4'
-
-services:
-  dataverse:
-    container_name: 'dataverse'
-    hostname: dataverse
-    image: ${DATAVERSE_IMAGE}
-    restart: on-failure
-    user: payara
-    environment:
-      - DATAVERSE_DB_HOST=postgres
-      - DATAVERSE_DB_USER=${DATAVERSE_DB_USER}
-      - DATAVERSE_DB_PASSWORD=${DATAVERSE_DB_PASSWORD}
-    ports:
-      - '8080:8080'
-    networks:
-      - dataverse
-    depends_on:
-      postgres:
-        condition: service_started
-      solr:
-        condition: service_started
-      dv_initializer:
-        condition: service_completed_successfully
-    volumes:
-      - ${RUNNER_TEMP}/dv/data:/dv
-      - ${CONFIG_DIR}:/secrets
-    tmpfs:
-      - /dumps:mode=770,size=2052M,uid=1000,gid=1000
-      - /tmp:mode=770,size=2052M,uid=1000,gid=1000
-    mem_limit: 2147483648 # 2 GiB
-    mem_reservation: 1024m
-    privileged: false
-
-  dv_initializer:
-    container_name: 'dv_initializer'
-    image: ${CONFIGBAKER_IMAGE}
-    restart: 'no'
-    command:
-      - sh
-      - -c
-      - 'fix-fs-perms.sh dv'
-    volumes:
-      - ${RUNNER_TEMP}/dv/data:/dv
-
-  postgres:
-    container_name: 'postgres'
-    hostname: postgres
-    image: postgres:${POSTGRES_VERSION}
-    restart: on-failure
-    environment:
-      - POSTGRES_USER=${DATAVERSE_DB_USER}
-      - POSTGRES_PASSWORD=${DATAVERSE_DB_PASSWORD}
-    ports:
-      - '5432:5432'
-    networks:
-      - dataverse
-
-  solr_initializer:
-    container_name: 'solr_initializer'
-    image: ${CONFIGBAKER_IMAGE}
-    restart: 'no'
-    command:
-      - sh
-      - -c
-      - 'fix-fs-perms.sh solr && cp -a /template/* /solr-template'
-    volumes:
-      - ${RUNNER_TEMP}/solr/data:/var/solr
-      - ${RUNNER_TEMP}/solr/conf:/solr-template
-
-  solr:
-    container_name: 'solr'
-    hostname: 'solr'
-    image: solr:${SOLR_VERSION}
-    depends_on:
-      solr_initializer:
-        condition: service_completed_successfully
-    restart: on-failure
-    ports:
-      - '8983:8983'
-    networks:
-      - dataverse
-    command:
-      - 'solr-precreate'
-      - 'collection1'
-      - '/template'
-    volumes:
-      - ${RUNNER_TEMP}/solr/data:/var/solr
-      - ${RUNNER_TEMP}/solr/conf:/template
-
-  smtp:
-    container_name: 'smtp'
-    hostname: 'smtp'
-    image: maildev/maildev:2.0.5
-    restart: on-failure
-    expose:
-      - '25' # smtp server
-    environment:
-      - MAILDEV_SMTP_PORT=25
-      - MAILDEV_MAIL_DIRECTORY=/mail
-    networks:
-      - dataverse
-    tmpfs:
-      - /mail:mode=770,size=128M,uid=1000,gid=1000
-
-networks:
-  dataverse:
-    driver: bridge
+name: dv-configbaker
+description: |
+  "This GitHub Action serves as a powerful tool to create a functional Dataverse instance, enabling developers to run tests and perform other critical tasks within their GitHub CI workflows."
+inputs:
+  image_tag:
+    description: "Tag of image for Dataverse app and Configbaker"
+    required: true
+    default: "unstable"
+  image_dataverse:
+    description: "Name of Dataverse app image (can include registry)"
+    required: true
+    default: "docker.io/gdcc/dataverse"
+  image_configbaker:
+    description: "Name of Configbaker image (can include registry)"
+    required: true
+    default: "docker.io/gdcc/configbaker"
+  postgresql_version:
+    description: "Override the PostgreSQL version to use"
+    required: false
+  solr_version:
+    description: "Override the Solr version to use"
+    required: false
+  jvm_options:
+    description: "Line separated key-value pairs of JVM options to be set before startup. Example: dataverse.spi.exporters.directory=/..."
+    required: false
+  create-dv:
+    description: "Whether or not to create an example Dataverse"
+    required: true
+    default: "true"
+outputs:
+  api_token:
+    description: "API Token of dataverseAdmin superuser"
+    value: ${{ steps.bootstrap.outputs.API_TOKEN }}
+  base_url:
+    description: "Base URL where to reach the instance via HTTP"
+    value: ${{ steps.bootstrap.outputs.base_url }}
+runs:
+  using: "composite"
+  steps:
+    - name: "Pull images for inspection and cache"
+      shell: bash
+      run: |
+        docker pull -q ${{ inputs.image_dataverse }}:${{ inputs.image_tag }}
+        docker pull -q ${{ inputs.image_configbaker }}:${{ inputs.image_tag }}
+    - name: "Prepare environment"
+      shell: bash
+      run: |
+        # Get PostgreSQL version from action config or application image metadata, fail otherwise
+        PG_VERSION="${{ inputs.postgresql_version }}"
+        PG_VERSION="${PG_VERSION:-$(docker inspect -f '{{ index .Config.Labels "org.dataverse.deps.postgresql.version"}}' '${{ inputs.image_dataverse }}:${{ inputs.image_tag }}')}"
+        if [[ -z "${PG_VERSION}" ]]; then
+          echo "Cannot find PostgreSQL version"; exit 1
+        else
+          echo "POSTGRES_VERSION=$PG_VERSION" | tee -a "${GITHUB_ENV}" 
+        fi
+        
+        # Get Solr version from action config or application image metadata, fail otherwise
+        SOLR_VERSION=${{ inputs.solr_version }}
+        SOLR_VERSION="${SOLR_VERSION:-$(docker inspect -f '{{ index .Config.Labels "org.dataverse.deps.solr.version"}}' '${{ inputs.image_dataverse }}:${{ inputs.image_tag }}')}"
+        if [[ -z "${SOLR_VERSION}" ]]; then
+          echo "Cannot find Solr version"; exit 1
+        else
+          echo "SOLR_VERSION=$SOLR_VERSION" | tee -a "${GITHUB_ENV}" 
+        fi
+        
+        echo "CONFIGBAKER_IMAGE=${{ inputs.image_configbaker }}:${{ inputs.image_tag }}" | tee -a "${GITHUB_ENV}"
+        echo "DATAVERSE_IMAGE=${{ inputs.image_dataverse }}:${{ inputs.image_tag }}" | tee -a "${GITHUB_ENV}"
+        echo "DATAVERSE_DB_USER=dataverse" | tee -a "${GITHUB_ENV}"
+        echo "DATAVERSE_DB_PASSWORD=secret" | tee -a "${GITHUB_ENV}"
+        
+        # We use the MicroProfile Config Source trick of reading properties from a directory.
+        # See also https://docs.payara.fish/community/docs/Technical%20Documentation/MicroProfile/Config/Directory.html
+        echo "CONFIG_DIR=${RUNNER_TEMP}/dv/conf" | tee -a "${GITHUB_ENV}"
+        mkdir -p "${RUNNER_TEMP}/dv/conf"
+        while IFS= read -r line; do
+          FILENAME="${RUNNER_TEMP}/dv/conf/$(echo "$line" | cut -f1 -d=)"
+          echo "$line" | cut -f2- -d= > "$FILENAME"
+        done < <(printf '%s' "${{ inputs.jvm_options }}")
+    - name: "Start Dataverse service in background"
+      shell: bash
+      run: |
+        echo "::group::🥎 Start Dataverse service in background"
+        docker compose -f ${{ github.action_path }}/docker-compose.yml -p apitest up -d --quiet-pull \
+          && echo -e "✅️ Dataverse containers have been started."
+        echo "::endgroup::"
+    # Bootstrap will wait up until accessible, so blocking here.
+    - name: "Bootstrap Dataverse service"
+      id: bootstrap
+      shell: bash
+      run: |
+        echo "::group::🤖 Bootstrap Dataverse service"
+        mkdir -p "${RUNNER_TEMP}/dv"
+        touch "${RUNNER_TEMP}/dv/bootstrap.exposed.env"
+        
+        docker run -i --network apitest_dataverse \
+          -v "${RUNNER_TEMP}/dv/bootstrap.exposed.env:/.env" \
+          "${CONFIGBAKER_IMAGE}" bootstrap.sh -e /.env dev
+        
+        # Expose outputs
+        grep "API_TOKEN" "${RUNNER_TEMP}/dv/bootstrap.exposed.env" >> "$GITHUB_OUTPUT"
+        echo "base_url=http://localhost:8080/" >> "$GITHUB_OUTPUT"
+        
+        echo "::endgroup::"
+    # - name: Retrieve API Token
+    #   run: ${{ github.action_path }}/scripts/get_api_token.sh
+    #   shell: bash
+    # - name: Create Dataverse
+    #   run: ${{ github.action_path }}/scripts/create_dataverse.sh
+    #   shell: bash
